# Generated by Django 3.1 on 2021-05-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_api', '0006_news_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='expired',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
