# Generated by Django 3.1 on 2021-05-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_api', '0007_auto_20210524_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
